### ISSUE TITLE
facebook messenger app

### ISSUE THREAD

**Issue by LovingGt** [Naituw/IPAPatch#30] opened 2017-07-21 00:59 UTC
Hi @Naituw i try facebook messenger app . like hacking facebook 

And I can't open application.

2017-07-21 03:34:38.314 Messenger[646:154606] (2/2) ,
    "<__NSGlobalBlock__: 0x30d1a0c>",
    "",
    "<null>",
    "[edge-mqtt-merge.facebook.com:graph.facebook.com]",
    "<__NSGlobalBlock__: 0x30d1a30>",
        (
        "https://graph.facebook.com"
    ),
    0,
    0
)
E0721 03:34:38.827294 944861184 PersistentKeyValueStore.cpp:1448] Failed to reverse migrate directory: domain: FBStorageKitIoErrorErrorDomain; code: 2; description: Could not open directory: No such file or directory .
E0721 03:34:39.009958 944861184 PersistentKeyValueStore.cpp:1448] Failed to reverse migrate directory: domain: FBStorageKitIoErrorErrorDomain; code: 2; description: Could not open directory: No such file or directory .
2017-07-21 03:36:43.398 Messenger[646:155150] Check Pinnning Called: (
    "<NSURLAuthenticationChallenge: 0x15e70240>"
)

**Comment by Naituw** [comment] 2017-08-03 06:10
Would you setup a repository that can reproduce this issue?

**Comment by Naituw** [comment] 2019-07-29 03:43
Closing since no reply

**Closed by Naituw** 2019-07-29 03:43 UTC
Labels: Needs More Info
